import { StyleSheet } from 'react-native';

export const feedbackSheetStyles = StyleSheet.create({
  handleIndicator: {
    backgroundColor: '#CFD1DC',
    width: 56,
    height: 5,
    borderRadius: 100,
    opacity: 1,
  },
  contentContainer: {
    width: '100%',
    height: 335,
    opacity: 1,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 34,
    alignSelf: 'center',
  },
  textContainer: {
    alignItems: 'center',
    paddingBottom: 24,
  },
  title: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 24,
    lineHeight: 34,
    textAlign: 'center',
    color: '#000000',
    marginBottom: 12,
  },
  description: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    color: '#868AA5',
  },
  inputContainer: {
    width: '100%',
    height: 64,
    marginBottom: 24,
    alignSelf: 'center',
  },
  placeholder: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: '#CFD1DC',
  },
  textArea: {
    height: 64,
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    includeFontPadding: false,
  },
  buttonContainer: {
    marginTop: 'auto',
  },
  submitButton: {
    width: '100%',
    height: 48,
    opacity: 1,
    gap: 8,
    borderRadius: 100,
    paddingTop: 12,
    paddingRight: 24,
    paddingBottom: 12,
    paddingLeft: 24,
    backgroundColor: '#000000',
    marginBottom: 16,
  },
  submitButtonText: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    color: '#FFFFFF',
  },
});
