import { StyleSheet } from 'react-native';

export const onboardSheetStyles = StyleSheet.create({
  handleIndicator: {
    backgroundColor: '#CFD1DC',
    width: 56,
    height: 5,
    borderRadius: 100,
    opacity: 1,
  },
  contentContainer: {
    width: '100%',
    height: 399,
    opacity: 1,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 34,
    alignSelf: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    height: 120,
    marginBottom: 24,
  },
  logo: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  textContainer: {
    alignItems: 'center',
    paddingBottom: 24,
  },
  title: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 24,
    lineHeight: 34,
    textAlign: 'center',
    color: '#000000',
    marginBottom: 8,
  },
  description: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    color: '#868AA5',
  },
  buttonsContainer: {
    width: '100%',
    height: 48,
    opacity: 1,
    gap: 8,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  leftButton: {
    width: 167.5,
    height: 48,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#E1E3EB',
    borderRadius: 100,
  },
  leftButtonText: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: '#000000',
  },
  rightButtonText: {
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  rightButton: {
    width: 167.5,
    height: 48,
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 100,
  },
});
