import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const reviewSheetStyles = StyleSheet.create({
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingBottom: 34,
  },
  handleIndicator: {
    backgroundColor: '#E5E5EA',
    width: 40,
  },
  imageContainer: {
    width: '100%',
    height: 120,
    opacity: 1,
    paddingRight: 16,
    paddingLeft: 16,
    gap: 8,
    alignItems: 'center',
    marginBottom: 20,
  },
  iconWrapper: {
    width: 120,
    height: 120,
    borderRadius: 8,
    opacity: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    fontSize: 48,
  },
  reviewImage: {
    width: 108,
    height: 108,
  },
  textContainer: {
    width: '100%',
    height: 64,
    opacity: 1,
    paddingRight: 16,
    paddingLeft: 16,
    alignItems: 'center',
  },
  title: {
    width: 343,
    height: 32,
    opacity: 1,
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#000000',
    marginBottom: 8,
  },
  description: {
    width: 343,
    height: 24,
    opacity: 1,
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#868AA5',
  },
  buttonContainer: {
   marginTop: 'auto',
  },
  reviewButton: {
    width: '100%',
    height: 48,
    opacity: 1,
    gap: 8,
    borderRadius: 100,
    paddingTop: 12,
    paddingRight: 24,
    paddingBottom: 12,
    paddingLeft: 24,
    backgroundColor: '#000000',
  },
  reviewButtonText: {
    width: 108,
    height: 24,
    opacity: 1,
    fontFamily: 'Helvetica',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#FFFFFF',
  },
});
